[package]
name = "conventional-check-perf"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "conventional-check"
path = "benches/conventional.rs"

[dependencies]
git-cliff-core = { version = "=2.14.2", default-features = false }
git-conventional = "=0.12.9"
cargo_metadata = "0.23.0"
regex = "1.11.2"
