// Auto-generated by fetch-popular-projects.ts -- do not edit manually.
// Re-generate with: npm run fetch-popular-projects

export interface PopularProject {
  name: string;
  stars: number;
  url: string;
}

const POPULAR_PROJECTS: PopularProject[] = [
  {
    "name": "XAMPPRocky/tokei",
    "stars": 14775,
    "url": "https://github.com/XAMPPRocky/tokei"
  },
  {
    "name": "0xPlaygrounds/rig",
    "stars": 8213,
    "url": "https://github.com/0xPlaygrounds/rig"
  },
  {
    "name": "biomejs/gritql",
    "stars": 4569,
    "url": "https://github.com/biomejs/gritql"
  },
  {
    "name": "lycheeverse/lychee",
    "stars": 3821,
    "url": "https://github.com/lycheeverse/lychee"
  },
  {
    "name": "TimelyDataflow/timely-dataflow",
    "stars": 3638,
    "url": "https://github.com/TimelyDataflow/timely-dataflow"
  },
  {
    "name": "TimelyDataflow/differential-dataflow",
    "stars": 2995,
    "url": "https://github.com/TimelyDataflow/differential-dataflow"
  },
  {
    "name": "cargo-bins/cargo-binstall",
    "stars": 2815,
    "url": "https://github.com/cargo-bins/cargo-binstall"
  },
  {
    "name": "bluealloy/revm",
    "stars": 2219,
    "url": "https://github.com/bluealloy/revm"
  },
  {
    "name": "elastio/bon",
    "stars": 2111,
    "url": "https://github.com/elastio/bon"
  },
  {
    "name": "kdheepak/taskwarrior-tui",
    "stars": 2102,
    "url": "https://github.com/kdheepak/taskwarrior-tui"
  },
  {
    "name": "LukeMathWalker/pavex",
    "stars": 2068,
    "url": "https://github.com/LukeMathWalker/pavex"
  },
  {
    "name": "shell-pool/shpool",
    "stars": 1912,
    "url": "https://github.com/shell-pool/shpool"
  },
  {
    "name": "InioX/matugen",
    "stars": 1910,
    "url": "https://github.com/InioX/matugen"
  },
  {
    "name": "avhz/RustQuant",
    "stars": 1797,
    "url": "https://github.com/avhz/RustQuant"
  },
  {
    "name": "ccbrown/iocraft",
    "stars": 1483,
    "url": "https://github.com/ccbrown/iocraft"
  },
  {
    "name": "XAMPPRocky/octocrab",
    "stars": 1427,
    "url": "https://github.com/XAMPPRocky/octocrab"
  },
  {
    "name": "ratatui/ratzilla",
    "stars": 1421,
    "url": "https://github.com/ratatui/ratzilla"
  },
  {
    "name": "ratatui/mousefood",
    "stars": 1306,
    "url": "https://github.com/ratatui/mousefood"
  },
  {
    "name": "ratatui/tachyonfx",
    "stars": 1280,
    "url": "https://github.com/ratatui/tachyonfx"
  },
  {
    "name": "orhun/daktilo",
    "stars": 1251,
    "url": "https://github.com/orhun/daktilo"
  },
  {
    "name": "testcontainers/testcontainers-rs",
    "stars": 1116,
    "url": "https://github.com/testcontainers/testcontainers-rs"
  },
  {
    "name": "bosun-ai/swiftide",
    "stars": 767,
    "url": "https://github.com/bosun-ai/swiftide"
  },
  {
    "name": "harnesslabs/arbiter",
    "stars": 747,
    "url": "https://github.com/harnesslabs/arbiter"
  },
  {
    "name": "Nullus157/async-compression",
    "stars": 663,
    "url": "https://github.com/Nullus157/async-compression"
  },
  {
    "name": "atsamd-rs/atsamd",
    "stars": 657,
    "url": "https://github.com/atsamd-rs/atsamd"
  },
  {
    "name": "cel-rust/cel-rust",
    "stars": 657,
    "url": "https://github.com/cel-rust/cel-rust"
  },
  {
    "name": "rust-lang/cfg-if",
    "stars": 642,
    "url": "https://github.com/rust-lang/cfg-if"
  },
  {
    "name": "makspll/bevy_mod_scripting",
    "stars": 641,
    "url": "https://github.com/makspll/bevy_mod_scripting"
  },
  {
    "name": "fossable/goldboot",
    "stars": 641,
    "url": "https://github.com/fossable/goldboot"
  },
  {
    "name": "CapSoftware/scap",
    "stars": 630,
    "url": "https://github.com/CapSoftware/scap"
  },
  {
    "name": "rust-lang/glob",
    "stars": 587,
    "url": "https://github.com/rust-lang/glob"
  },
  {
    "name": "Harry-kp/vortix",
    "stars": 584,
    "url": "https://github.com/Harry-kp/vortix"
  },
  {
    "name": "water-rs/waterui",
    "stars": 487,
    "url": "https://github.com/water-rs/waterui"
  },
  {
    "name": "bearcove/loona",
    "stars": 451,
    "url": "https://github.com/bearcove/loona"
  },
  {
    "name": "near/borsh-rs",
    "stars": 429,
    "url": "https://github.com/near/borsh-rs"
  },
  {
    "name": "crabnebula-dev/devtools",
    "stars": 423,
    "url": "https://github.com/crabnebula-dev/devtools"
  },
  {
    "name": "lox-space/lox",
    "stars": 383,
    "url": "https://github.com/lox-space/lox"
  },
  {
    "name": "contentauth/c2pa-rs",
    "stars": 380,
    "url": "https://github.com/contentauth/c2pa-rs"
  },
  {
    "name": "rust-lang/cmake-rs",
    "stars": 380,
    "url": "https://github.com/rust-lang/cmake-rs"
  },
  {
    "name": "ratatui/ratatui-image",
    "stars": 377,
    "url": "https://github.com/ratatui/ratatui-image"
  }
];

export default POPULAR_PROJECTS;
