[package]
name = "changelog-regex-bench"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
cargo_metadata = "0.23.0"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
fs-err = { version = "3.1.1", features = ["tokio"] }
git-cliff-core = { version = "2.14.2", default-features = false }
parse-changelog = { version = "0.6.13", default-features = false }
regex = "1.11.2"
serde = "1.0.219"
serde_json = "1.0.143"
tracing = "0.1.41"
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support", "html_reports", "plotters"] }

[dev-dependencies]
expect-test = "1.5.1"

[[bench]]
name = "pr_regex"
path = "src/main.rs"
harness = false
