[package]
name = "changelog-header-bench"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
cargo_metadata = "0.23"
fs-err = "3.3"
parse-changelog = { version = "0.6.17", default-features = false }
regex = "1.12"
criterion = { version = "0.8.2", default-features = false, features = ["cargo_bench_support", "html_reports", "plotters"] }

[[bench]]
name = "headers"
path = "src/main.rs"
harness = false
